enemy_color: "red"
# enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5_0526.xml
device: GPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 500
  y: 400
  width: 500
  height: 500

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 0.5 # degree
pitch_offset: -1.0 # degree
comming_angle: 60 # degree
leaving_angle: 20 # degree
decision_speed: 7 # rad/s
high_speed_delay_time: 0.090 # s
low_speed_delay_time: 0.080 # s

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击
high_spin_force_fire_enabled: false
high_spin_force_fire_enter_speed: 12.0 # rad/s
high_spin_force_fire_exit_speed: 9.0 # rad/s

camera_name: "hikrobot"
exposure_ms: 2
gain: 16
vid_pid: "2bdf:0001"

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

# 重投影误差: 0.2460px
camera_matrix: [1797.5969210084497, 0, 704.29881863698699, 0, 1797.7867973769753, 537.02448196123203, 0, 0, 1]
distort_coeffs: [-0.087666128664286636, 0.22065090602894918, -0.00012832454592968064, 0.00058739756422585129, 0]

# 相机同理想情况的偏角: yaw-1.95 pitch-1.85 roll0.00 degree
R_camera2gimbal: [ -0.008726535498, 0.017451741903, 0.999809624020, -0.999961923064, -0.000152299044, -0.008725206405, 0.000000000000, -0.999847695156, 0.017452406437 ]
t_camera2gimbal: [0.092317072966267857, -0.0037162449022158732, 0.08695273622026739]

#####-----时序参数-----#####
timing:
  offset: -0.002 # s, 串口姿态固定时间补偿


#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"

#####-----buff_detector参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.520   # s
predict_time: 0.100     # s
